import{i as u,a as p,A as g}from"./assets/vendor-b5a3dDts.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))c(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();let m={};const n={formEl:document.querySelector(".order-form"),backdropEl:document.querySelector(".order-backdrop"),closeBtn:document.querySelector(".modal-close-button"),nameInput:document.getElementById("name"),phoneInput:document.getElementById("phone"),orderBtn:document.querySelector(".order-button")};n.phoneInput.addEventListener("input",()=>{let e=n.phoneInput.value.replace(/\D/g,"");e.startsWith("0")?e="38"+e:e.startsWith("8")&&(e="3"+e),e=e.slice(0,12),n.phoneInput.value=e,d()});n.nameInput.addEventListener("input",d);d();n.closeBtn.addEventListener("click",l);n.backdropEl.addEventListener("click",e=>{e.target===n.backdropEl&&l()});document.addEventListener("keydown",e=>{e.key==="Escape"&&n.backdropEl.classList.contains("is-open")&&l()});n.formEl.addEventListener("submit",async e=>{e.preventDefault();const{name:t,phone:s,comment:c}=e.target.elements;if(!/^380\d{9}$/.test(s.value)){u.show({message:"Введіть номер у форматі 380XXXXXXXXX"});return}t.value.length===1&&u.show({message:"Ім'я має складатись мінімум з 2 символів!",color:"red"});const o=h(c.value);m={name:t.value,phone:s.value,comment:o,modelId:"682f9bbf8acbdf505592ac36",color:"#1212ca"},console.log(m);try{const f=(await p.post("https://furniture-store-v2.b.goit.study/api/orders",m)).data;console.log(f),u.show({message:`Ви замовили ${f.model}! 
    Номер вашого замовлення ${f.orderNum}. 
    Вже телефонуємно Вам!`,color:"green"}),e.target.reset(),d(),l()}catch(a){console.log(a.message),u.show({message:"некорректні дані, будь ласка, перевірте ім'я і номер телефону!",color:"red"})}});function y(){document.body.style.overflow=""}function l(){n.backdropEl.classList.remove("is-open"),y()}function d(){const e=n.nameInput.value.trim()!=="",t=n.phoneInput.value.trim()!=="";n.orderBtn.disabled=!(e&&t)}function h(e){if(e.length>256)return e.slice(0,255);for(;e.length<5;)e+=" ";return e}const b="https://furniture-store-v2.b.goit.study/api/categories",L="https://furniture-store-v2.b.goit.study/api/furnitures";async function v(){try{const{data:e}=await p.get(b);return e}catch(e){return console.error("Error fetching categories:",e),[]}}async function E(){const{data:e}=await p.get(L,{params:{page:1,limit:8}});return e.furnitures}const i={header:document.querySelector(".header"),furnitureCategoryList:document.querySelector(".furniture-category__list"),furnitureList:document.querySelector(".furniture-list"),accordionContainer:document.querySelector(".accordion"),orderBackdrop:document.querySelector(".order-backdrop"),orderModalOverlay:document.querySelector(".order-modal-overlay"),productModal:document.querySelector(".product-modal"),productModalCloseBtn:document.querySelector(".product-modal__close")},k={"М'які меблі":"soft-furniture","Шафи та системи зберігання":"storage-systems","Ліжка та матраци":"beds-mattresses",Столи:"tables","Стільці та табурети":"chairs-stools",Кухні:"kitchens","Меблі для дитячої":"kids-furniture","Меблі для офісу":"office-furniture","Меблі для передпокою":"hallway-furniture","Меблі для ванної кімнати":"bathroom-furniture","Садові та вуличні меблі":"garden-furniture","Декор та аксесуари":"decor-accessories"};function S({id:e,name:t}){return`
    <li class="furniture-category__item ${k[t]||""}" data-id="${e}">
      <a href="#" class="furniture-category__link">${t}</a>
    </li>`}function w(e){return e.map(S).join("")}function q(e){if(!i.furnitureCategoryList){console.error("Елемент .furniture-category__list не знайдено!");return}const t=w(e);i.furnitureCategoryList.insertAdjacentHTML("beforeend",t)}async function C(){const e=await v();e.length>0&&q(e)}function I({_id:e,name:t,price:s,images:c,color:r}){const o=r.map(a=>`<span class="color-dot" style="background-color: ${a}"></span>`).join("");return`
    <li class="furniture-card" data-id="${e}">
      <img
        src="${c[0]}" 
        alt="${t}"
        class="card-image"
        loading="lazy"
      />
      <h2 class="card-title">${t}</h2>
      <div class="card-colors">
        ${o}
      </div>
      <p class="card-price">${s.toLocaleString()} грн</p>
      <button class="details-btn" type="button" data-id="${e}">Детальніше</button>
    </li>`}function $(e){return e.map(I).join("")}function _(e){if(!i.furnitureList){console.error("Елемент .furniture-list не знайдено!");return}const t=$(e);i.furnitureList.insertAdjacentHTML("beforeend",t)}async function M(){const e=await E();e&&e.length>0&&_(e),console.log(e)}function O(){const e=document.querySelector(".accordion");e&&new g(e,{duration:300,showMultiple:!1,collapse:!0})}function B(){i.furnitureCategoryList&&i.furnitureCategoryList.addEventListener("click",e=>{const t=e.target.closest(".furniture-category__item");if(!t)return;i.furnitureCategoryList.querySelectorAll(".furniture-category__item").forEach(c=>c.classList.remove("akcent-item-color")),t.classList.add("akcent-item-color")})}document.addEventListener("DOMContentLoaded",()=>{console.log("DOM fully loaded and parsed"),O(),C(),B(),M()});
//# sourceMappingURL=index.js.map
