import{i as l,a as g,A as I}from"./assets/vendor-b5a3dDts.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const c of r)if(c.type==="childList")for(const u of c.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function o(r){const c={};return r.integrity&&(c.integrity=r.integrity),r.referrerPolicy&&(c.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?c.credentials="include":r.crossOrigin==="anonymous"?c.credentials="omit":c.credentials="same-origin",c}function i(r){if(r.ep)return;r.ep=!0;const c=o(r);fetch(r.href,c)}})();let h={};const a={formEl:document.querySelector(".order-form"),backdropEl:document.querySelector(".order-backdrop"),closeBtn:document.querySelector(".modal-close-button"),nameInput:document.getElementById("name"),phoneInput:document.getElementById("phone"),orderBtn:document.querySelector(".order-button")};a.phoneInput.addEventListener("input",()=>{let e=a.phoneInput.value.replace(/\D/g,"");e.startsWith("0")?e="38"+e:e.startsWith("8")&&(e="3"+e),e=e.slice(0,12),a.phoneInput.value=e,m()});a.nameInput.addEventListener("input",m);m();a.closeBtn.addEventListener("click",f);a.backdropEl.addEventListener("click",e=>{e.target===a.backdropEl&&f()});document.addEventListener("keydown",e=>{e.key==="Escape"&&a.backdropEl.classList.contains("is-open")&&f()});a.formEl.addEventListener("submit",async e=>{e.preventDefault(),a.nameInput.classList.remove("input-error"),a.phoneInput.classList.remove("input-error");const{name:t,phone:o,comment:i}=e.target.elements;if(t.value.length===1){a.nameInput.classList.add("input-error"),l.show({message:"Ім'я має складатись мінімум з 2 символів!",color:"red",position:"topCenter"});return}if(!/^380\d{9}$/.test(o.value)){a.phoneInput.classList.add("input-error"),l.show({color:"red",message:"Введіть номер у форматі 380XXXXXXXXX",position:"topCenter"});return}const c=E(i.value);h={name:t.value,phone:o.value,comment:c,modelId:"682f9bbf8acbdf505592ac36",color:"#1212ca"};try{const y=(await g.post("https://furniture-store-v2.b.goit.study/api/orders",h)).data;l.show({message:`Ви замовили ${y.model}! 
    Номер вашого замовлення ${y.orderNum}. 
    Вже телефонуємно Вам!`,color:"yellow",position:"bottomCenter"}),e.target.reset(),m(),f()}catch(u){console.log(u.message),l.show({message:"некорректні дані, будь ласка, перевірте ім'я і номер телефону!",color:"red",position:"topCenter"})}});function M(){document.body.style.overflow=""}function f(){a.backdropEl.classList.remove("is-open"),M()}function m(){const e=a.nameInput.value.trim()!=="",t=a.phoneInput.value.trim()!=="";a.nameInput.classList.remove("input-error"),a.phoneInput.classList.remove("input-error"),a.orderBtn.disabled=!(e&&t)}function E(e){if(e.length>256)return e.slice(0,255);for(;e.length<5;)e+=" ";return e}const k="https://furniture-store-v2.b.goit.study/api/categories",w="https://furniture-store-v2.b.goit.study/api/furnitures";async function S(){try{const{data:e}=await g.get(k);return e}catch(e){return console.error("Error fetching categories:",e),[]}}async function _({page:e=1,limit:t=8,category:o=""}={}){const{data:i}=await g.get(w,{params:{page:e,limit:t,...o?{category:o}:{}}});return i}const s={header:document.querySelector(".header"),furnitureCategoryTitle:document.querySelector(".furniture-category__title"),furnitureCategoryList:document.querySelector(".furniture-category__list"),furnitureList:document.querySelector(".furniture-list"),loadMoreBtn:document.querySelector(".load-more-btn"),accordionContainer:document.querySelector(".accordion"),orderBackdrop:document.querySelector(".order-backdrop"),orderModalOverlay:document.querySelector(".order-modal-overlay"),productModal:document.querySelector(".product-modal"),productModalCloseBtn:document.querySelector(".product-modal__close")},p=8,n={category:"",currentPage:0,totalItems:0,loadedItems:0,isLoading:!1},C={"М'які меблі":"soft-furniture","Шафи та системи зберігання":"storage-systems","Ліжка та матраци":"beds-mattresses",Столи:"tables","Стільці та табурети":"chairs-stools",Кухні:"kitchens","Меблі для дитячої":"kids-furniture","Меблі для офісу":"office-furniture","Меблі для передпокою":"hallway-furniture","Меблі для ванної кімнати":"bathroom-furniture","Садові та вуличні меблі":"garden-furniture","Декор та аксесуари":"decor-accessories"};function q({_id:e,name:t}){return`
    <li
      class="furniture-category__item ${C[t]||""}"
      data-id="${e}"
    >
      <a href="#" class="furniture-category__link">${t}</a>
    </li>`}function B(e){return e.map(q).join("")}function $(e){if(!s.furnitureCategoryList){console.error("Елемент .furniture-category__list не знайдено!");return}const t=B(e);s.furnitureCategoryList.insertAdjacentHTML("beforeend",t)}async function T(){const e=await S();e.length>0&&$(e)}function P({_id:e,name:t,price:o,images:i,color:r}){const c=r.map(u=>`<span class="color-dot" style="background-color: ${u}"></span>`).join("");return`
    <li class="furniture-card" data-id="${e}">
      <img
        src="${i[0]}"
        alt="${t}"
        class="card-image"
        loading="lazy"
      />
      <h2 class="card-title">${t}</h2>
      <div class="card-colors">
        ${c}
      </div>
      <p class="card-price">${o.toLocaleString()} грн</p>
      <button class="details-btn" type="button" data-id="${e}">Детальніше</button>
    </li>`}function L(e){return e.map(P).join("")}function O(){var e;(e=s.furnitureCategoryTitle)==null||e.scrollIntoView({behavior:"smooth",block:"start"})}function v(){s.loadMoreBtn&&(s.loadMoreBtn.disabled=n.isLoading,s.loadMoreBtn.textContent=n.isLoading?"Завантаження...":n.loadedItems>=n.totalItems&&n.totalItems>p?"Згорнути":"Показати ще",s.loadMoreBtn.hidden=n.totalItems<=p)}function X(e,t=!1){if(!s.furnitureList){console.error("Елемент .furniture-list не знайдено!");return}if(t){s.furnitureList.insertAdjacentHTML("beforeend",L(e));return}s.furnitureList.innerHTML=L(e)}async function b({category:e=n.category,reset:t=!1}={}){if(n.isLoading)return[];t&&(n.category=e,n.currentPage=0,n.totalItems=0,n.loadedItems=0),n.isLoading=!0,v();try{const o=n.currentPage+1,{furnitures:i=[],totalItems:r=0}=await _({page:o,limit:p,...e?{category:e}:{}});return n.category=e,n.currentPage=o,n.totalItems=r,n.loadedItems=t?i.length:n.loadedItems+i.length,i.length>0?X(i,!t):t&&s.furnitureList&&(s.furnitureList.innerHTML=""),i}catch(o){return console.error("Error fetching furnitures:",o),[]}finally{n.isLoading=!1,v()}}async function d(e={}){const t=e.category??"";return b({category:t,reset:!0})}async function A(){if(n.loadedItems>=n.totalItems){const e=await d({category:n.category});return O(),e}return b()}function F(){const e=document.querySelector(".accordion");e&&new I(e,{duration:300,showMultiple:!1,collapse:!0})}function H(){s.furnitureCategoryList&&s.furnitureCategoryList.addEventListener("click",async e=>{const t=e.target.closest(".furniture-category__link"),o=e.target.closest(".furniture-category__item");if(!o||!t)return;e.preventDefault(),s.furnitureCategoryList.querySelectorAll(".furniture-category__item").forEach(c=>c.classList.remove("akcent-item-color")),o.classList.add("akcent-item-color");const r=o.dataset.id;if(!r){await d();return}await d({category:r})})}function N(){s.loadMoreBtn&&s.loadMoreBtn.addEventListener("click",async()=>{await A()})}function D(){if(!s.header)return;const e=s.header.querySelector(".header_menu_svg"),t=s.header.querySelector(".header_x_svg"),o=s.header.querySelector(".nav_list");if(!e||!t||!o)return;const i=()=>{t.classList.add("hide"),t.classList.remove("show"),e.classList.add("show"),e.classList.remove("hide"),o.classList.remove("is-open"),document.body.classList.remove("menu-open")};e.addEventListener("click",()=>{e.classList.add("hide"),e.classList.remove("show"),t.classList.add("show"),t.classList.remove("hide"),o.classList.add("is-open"),document.body.classList.add("menu-open")}),t.addEventListener("click",i),o.addEventListener("click",r=>{r.target.closest("a")&&i()})}document.addEventListener("DOMContentLoaded",()=>{console.log("DOM fully loaded and parsed"),F(),T(),H(),N(),d(),D()});
//# sourceMappingURL=index.js.map
